export const PROJECT_CREATE_REQUEST = 'PROJECT_CREATE_REQUEST';
export const PROJECT_CREATE_SUCCESS = 'PROJECT_CREATE_SUCCESS';
export const PROJECT_CREATE_FAIL = 'PROJECT_CREATE_FAIL';

export const PROJECT_READ_REQUEST = 'PROJECT_READ_REQUEST';
export const PROJECT_READ_SUCCESS = 'PROJECT_READ_SUCCESS';
export const PROJECT_READ_FAIL = 'PROJECT_READ_FAIL';

export const PROJECTS_SEARCH_REQUEST = 'PROJECTS_SEARCH_REQUEST';
export const PROJECTS_SEARCH_SUCCESS = 'PROJECTS_SEARCH_SUCCESS';
export const PROJECTS_SEARCH_FAIL = 'PROJECTS_SEARCH_FAIL';

export const PROJECT_UPDATE_REQUEST = 'PROJECT_UPDATE_REQUEST';
export const PROJECT_UPDATE_SUCCESS = 'PROJECT_UPDATE_SUCCESS';
export const PROJECT_UPDATE_FAIL = 'PROJECT_UPDATE_FAIL';

export const PROJECT_DELETE_REQUEST = 'PROJECT_DELETE_REQUEST';
export const PROJECT_DELETE_SUCCESS = 'PROJECT_DELETE_SUCCESS';
export const PROJECT_DELETE_FAIL = 'PROJECT_DELETE_FAIL';