export const SCREAM_CREATE_REQUEST = 'SCREAM_CREATE_REQUEST';
export const SCREAM_CREATE_SUCCESS = 'SCREAM_CREATE_SUCCESS';
export const SCREAM_CREATE_FAIL = 'SCREAM_CREATE_FAIL';

export const SCREAM_READ_REQUEST = 'SCREAM_READ_REQUEST';
export const SCREAM_READ_SUCCESS = 'SCREAM_READ_SUCCESS';
export const SCREAM_READ_FAIL = 'SCREAM_READ_FAIL';

export const SCREAM_UPDATE_REQUEST = 'SCREAMS_UPDATE_REQUEST';
export const SCREAM_UPDATE_SUCCESS = 'SCREAMS_UPDATE_SUCCESS';
export const SCREAM_UPDATE_FAIL = 'SCREAMS_UPDATE_FAIL';

export const SCREAM_DELETE_REQUEST = 'SCREAMS_DELETE_REQUEST';
export const SCREAM_DELETE_SUCCESS = 'SCREAMS_DELETE_SUCCESS';
export const SCREAM_DELETE_FAIL = 'SCREAMS_DELETE_FAIL';