export const TEAM_CREATE_REQUEST = 'TEAM_CREATE_REQUEST';
export const TEAM_CREATE_SUCCESS = 'TEAM_CREATE_SUCCESS';
export const TEAM_CREATE_FAIL = 'TEAM_CREATE_FAIL';

export const TEAM_READ_REQUEST = 'TEAM_READ_REQUEST';
export const TEAM_READ_SUCCESS = 'TEAM_READ_SUCCESS';
export const TEAM_READ_FAIL = 'TEAM_READ_FAIL';

export const TEAM_UPDATE_REQUEST = 'TEAM_UPDATE_REQUEST';
export const TEAM_UPDATE_SUCCESS = 'TEAM_UPDATE_SUCCESS';
export const TEAM_UPDATE_FAIL = 'TEAM_UPDATE_FAIL';

export const TEAM_SEARCH_REQUEST = 'TEAM_SEARCH_REQUEST';
export const TEAM_SEARCH_SUCCESS = 'TEAM_SEARCH_SUCCESS';
export const TEAM_SEARCH_FAIL = 'TEAM_SEARCH_FAIL';